### ISSUE TITLE
"Top_Itr" and "Bot_Itr" missing in parser

### ISSUE THREAD

**Issue by JanJamaszyk-FlyNow** [Jvanrhijn/CXXfoil#5]
In vanilla configuration the parser fails with the segfault. I could raise a PR for that but the fix is fairly simple, see attached
[cxxfoil-patch.txt](https://github.com/Jvanrhijn/CXXfoil/files/5124532/cxxfoil-patch.txt)

could you add this change to the master branch?

Thanks!

**Comment by Jvanrhijn** [comment]
Thanks for the patch, it's much appreciated!
